import streamlit as st
from PIL import Image

logo = Image.open('./digital_assets/app/toolbox_logo.png')

st.title('LLM Model Operations Toolbox')
st.markdown('Tool for calculating various metrics that are valuable to operationalizing LLMs.')

st.image(logo, width=500)

st.markdown("""DISCLAIMER

The "LLM Model Operations Toolbox" (the "Application") is provided for informational and operational purposes only. The outputs, insights, and recommendations generated by this Application are based on artificial intelligence and machine learning models, which may contain inaccuracies, errors, or omissions. The developers and distributors of this Application make no guarantees regarding the accuracy, reliability, completeness, or suitability of any information provided.

By using this Application, you acknowledge and agree that:

You assume full responsibility for any and all decisions made based on the use of this Application.
The developers, distributors, and affiliated parties shall not be held liable for any direct, indirect, incidental, special, consequential, or exemplary damages arising from the use or inability to use this Application.
No warranty, express or implied, is provided, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.
This Application does not provide professional, legal, financial, or any other form of certified advice, and any reliance on its outputs is at your own risk.
The use of this Application does not grant any license or rights to any proprietary information or intellectual property beyond what is explicitly stated.
By proceeding with the use of the "LLM Model Operations Toolbox," you acknowledge that you do so at your own risk and agree to release the developers, distributors, and affiliates from any liability or claims arising from your use of the Application.')
""")
